In [ ]:
import numpy as np

In [3]:
# Create array list
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## Compare Array and List which is faster.

In [11]:
%timeit [i**5 for i in range(1,10000)]

1.45 ms ± 167 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%timeit np.arange(1,10000)**5

35.4 μs ± 3.02 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [25]:
# Create array 
a=[]
for i in range(5):
    t=input("Enter your number:")
    a.append(t)
print(a)
print(type(a))
arr=np.array(a)
print(arr)
print(type(arr))

Enter your number: 5
Enter your number: 4
Enter your number: 7
Enter your number: 8
Enter your number: 6


['5', '4', '7', '8', '6']
<class 'list'>
['5' '4' '7' '8' '6']
<class 'numpy.ndarray'>


## Create different dimensional of array

In [20]:
arr=np.array([1,2,3,5,6])
print(arr)
print(arr.ndim)

[1 2 3 5 6]
1


In [21]:
arr=np.array([[1,2,3,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3 5 6]]
2


In [22]:
arr=np.array([[[1,2,3,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3 5 6]]]
3


In [23]:
arr=np.array([1,2,3,5,6],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 5 6]]]]]
5


In [24]:
arr=np.array(([1,2,3,5,6],[7,8,9,10,11]),ndmin=15)
print(arr)
print(arr.ndim)

[[[[[[[[[[[[[[[ 1  2  3  5  6]
              [ 7  8  9 10 11]]]]]]]]]]]]]]]
15


## Numpy array Function

In [1]:
import numpy as np


In [3]:
# Create 1-D Array
arr=np.ones(4)
print(arr)
print(type(arr))
print(arr.ndim)

[1. 1. 1. 1.]
<class 'numpy.ndarray'>
1


In [5]:
# create 2-D array
arr=np.ones((5,5))
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2


In [7]:
# create 3-D array
arr=np.ones((2,5,6))
print(arr)
print(type(arr))
print(arr.ndim)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
<class 'numpy.ndarray'>
3


In [11]:
# create 2-D array
arr=np.ones((5,6,3))
print(arr)
print(type(arr))
print(arr.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
3


In [12]:
# create 1-D array
arr=np.zeros((5))
print(arr)
print(type(arr))
print(arr.ndim)

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1


In [13]:
# create 2-D array
arr=np.zeros((5,6))
print(arr)
print(type(arr))
print(arr.ndim)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
2


In [14]:
# create 3-D array
arr=np.zeros((5,6,4))
print(arr)
print(type(arr))
print(arr.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.ndarray'>
3


In [15]:
# create 1-D array
arr=np.eye((5))
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
2


In [17]:
# create 2-D array
arr=np.eye(5,6)
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
<class 'numpy.ndarray'>
2


In [18]:
# create 3-D array
arr=np.eye(5,4,8)
print(arr)
print(type(arr))
print(arr.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
2


In [20]:
# create Random Variable 1-D
arr=np.random.rand(20)
print(arr)
print(type(arr))
print(arr.ndim)

[0.11347812 0.50293326 0.37883697 0.18239948 0.49459822 0.40510974
 0.83768301 0.77804043 0.96299356 0.90060468 0.42534068 0.88578735
 0.13877133 0.98899683 0.02006722 0.88676181 0.24797009 0.12472251
 0.20063082 0.86136776]
<class 'numpy.ndarray'>
1


In [21]:
# create Random Variable 2-D
arr=np.random.rand(20,5)
print(arr)
print(type(arr))
print(arr.ndim)

[[0.3432573  0.762965   0.33644281 0.94663307 0.59638486]
 [0.5651039  0.95957379 0.59685379 0.2364049  0.52865678]
 [0.57515856 0.45922399 0.09924277 0.21061487 0.69273056]
 [0.66606334 0.61734732 0.56603275 0.60900243 0.29990966]
 [0.74042197 0.72283557 0.47197558 0.02660468 0.32379012]
 [0.77906504 0.10479942 0.21697978 0.34049182 0.68332699]
 [0.63429219 0.55511526 0.5892712  0.50017427 0.18756079]
 [0.79610047 0.18818628 0.97655749 0.04487209 0.17562989]
 [0.22618163 0.72420933 0.43014293 0.77918964 0.58959086]
 [0.87898359 0.68631536 0.48101559 0.54986914 0.32158992]
 [0.51263859 0.75155939 0.01072435 0.46296432 0.71238497]
 [0.27347141 0.98868817 0.56629478 0.61441415 0.27769678]
 [0.05106387 0.32295313 0.53475395 0.23946851 0.21624395]
 [0.02299115 0.37250702 0.4183745  0.4912574  0.4867916 ]
 [0.61232618 0.17435389 0.52117885 0.96029269 0.8312103 ]
 [0.28736221 0.05874914 0.22457854 0.5317065  0.9493331 ]
 [0.30724035 0.41560331 0.87601294 0.2210088  0.21851861]
 [0.66296889 0

In [24]:
# create Random Variable 3-D
arr=np.random.rand(2,3,5)
print(arr)
print(type(arr))
print(arr.ndim)

[[[0.21084821 0.9493255  0.43397259 0.27455687 0.16399141]
  [0.8202677  0.90511475 0.0457795  0.83958059 0.47807367]
  [0.4384858  0.30030417 0.9197396  0.42596536 0.88897157]]

 [[0.50969956 0.0029021  0.46435425 0.84491976 0.41388236]
  [0.41374588 0.34502902 0.0618647  0.21093948 0.80827626]
  [0.00269378 0.18659752 0.97408174 0.67120032 0.92556543]]]
<class 'numpy.ndarray'>
3


## random.randn : it is giving number 0-1 or also give negative number

In [25]:
# create Random Variable 1-D
arr=np.random.randn(20)
print(arr)
print(type(arr))
print(arr.ndim)

[ 1.08729383 -0.48375522  0.51199405 -0.67448787 -1.26241378  0.51386571
  0.70369233  0.81099097  0.48257927  0.51471889  0.15921307 -0.87743337
  0.65418311  1.81894291 -1.26425158 -0.65801487 -0.60145257  0.23939715
 -2.06928629  0.42585894]
<class 'numpy.ndarray'>
1


In [26]:
# create Random Variable 2-D
arr=np.random.randn(2,5)
print(arr)
print(type(arr))
print(arr.ndim)

[[-0.24458916  0.04736093 -0.9241081   0.56184811 -0.63720137]
 [ 0.81615794 -2.32002434  0.70948294  1.91071022  0.49027756]]
<class 'numpy.ndarray'>
2


In [27]:
# create Random Variable 3-D
arr=np.random.randn(2,3,4)
print(arr)
print(type(arr))
print(arr.ndim)

[[[-0.60724363 -1.33867142  1.30190664 -0.2316659 ]
  [-0.25848422 -0.22815811  0.96002838  0.12491331]
  [-0.88825855  1.33378831  0.19684939 -0.91501726]]

 [[-0.09816423  1.04342343  0.04238475 -2.37202638]
  [ 0.2318346   1.16282826 -0.56435937  0.86551934]
  [-0.486602   -1.28987803  0.1970269   0.21566484]]]
<class 'numpy.ndarray'>
3


## random.randint : it is use to genrate the random integer number.

In [33]:
# create Random Variable 1-D
arr=np.random.randint(0,20,5)
print(arr)
print(type(arr))

[ 3  6 13  5  1]
<class 'numpy.ndarray'>


In [35]:
# create Random Variable 1-D
arr=np.random.randint(5,20,5)
print(arr)

[ 6 10 18 11 18]


In [44]:
# create Random Variable 1-D
arr=np.random.randint(((5,10,3),(2,10,3)))
print(arr)

[[3 4 1]
 [0 5 0]]


## random.randf : it is used to genrate the random float number giving always positive number

In [37]:
# create Random Variable 1-D
arr=np.random.ranf(5)
print(arr)
print(type(arr))

[0.02605421 0.10671906 0.71231469 0.15977049 0.81080103]
<class 'numpy.ndarray'>


In [40]:
# create Random Variable 2-D
arr=np.random.ranf((2,5))
print(arr)
print(type(arr))

[[0.473341   0.75215596 0.74603937 0.54944775 0.85543069]
 [0.71428533 0.90066826 0.14717622 0.34893777 0.2255727 ]]
<class 'numpy.ndarray'>


In [41]:
# create Random Variable 3-D
arr=np.random.ranf((2,5,6))
print(arr)
print(type(arr))

[[[0.08512013 0.16449544 0.90415076 0.39745601 0.9358442  0.99872353]
  [0.64069343 0.62481328 0.0080252  0.19062441 0.3270357  0.07481556]
  [0.47266056 0.19046844 0.37554879 0.54339925 0.10794327 0.64831875]
  [0.23490291 0.35882892 0.71973094 0.3697066  0.01414353 0.86137218]
  [0.31444999 0.20656503 0.67089932 0.96340577 0.69586247 0.39648589]]

 [[0.71378694 0.79755316 0.1736811  0.38211184 0.39768907 0.36171265]
  [0.01657863 0.06915246 0.27633395 0.51207196 0.45160729 0.40333724]
  [0.34443528 0.54214787 0.7091734  0.21592085 0.14563375 0.05751249]
  [0.41340661 0.55494341 0.18188836 0.32023398 0.62848121 0.01358239]
  [0.85301467 0.95461134 0.80767517 0.390411   0.75834149 0.0570082 ]]]
<class 'numpy.ndarray'>


## ravel and flatten use to multidimensional  to 1-D array

In [53]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print("The shape of array:",arr.ndim)
t=np.ravel(arr)
print(t)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
The shape of array: 2
[1 2 3 4 5 6 7 8]


In [55]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(type(arr))
print("The shape of array:",arr.ndim)
t=np.ravel(arr)
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
The shape of array: 2
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [58]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(type(arr))
print("The shape of array:",arr.ndim)
t=np.flatten()
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
The shape of array: 2
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## shape

In [61]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
